// Generated by CoffeeScript 1.7.1
(function() {
  var app, mocha, request, should;

  request = require('supertest');

  should = require('should');

  mocha = require('mocha');

  app = require(process.cwd() + '/.app');

  describe('UUID', function() {
    return it('should return a UUID', function(done) {
      return request(app).get('/uuid').expect(200).end(function(err, res) {
        if (err) {
          return done(err);
        }
        return done;
      });
    });
  });

}).call(this);
